In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 1D Array
a1 = np.array([1,2,3])
a1, a1.ndim

(array([1, 2, 3]), 1)

In [3]:
a2 = np.array([[1,2,3],[4,5,6]])
a2, a2.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 2)

In [7]:
a3 = np.array([
    [
        [1,2,3],[4,5,6], [2,2,2]
    ],[
        [7,8,9], [10,11,12],[13,14,15]
    ], [
        [16,17,18], [19,20,21], [2,2,2]
    ]])
a3, a3.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 2,  2,  2]],
 
        [[ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]],
 
        [[16, 17, 18],
         [19, 20, 21],
         [ 2,  2,  2]]]),
 3)

In [8]:
array_1 = pd.DataFrame(a1)
array_1

0
0  1
1  2
2  3

In [10]:
random_array_1 = np.ones((10,2))
random_array_1, random_array_1.shape

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 (10, 2))

In [12]:
random_array_2 = np.zeros((7,2,3))
random_array_2, random_array_2.shape

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (7, 2, 3))

In [15]:
random_array_3 = np.arange(0,100,3)
random_array_3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
random_array_4 = np.random.randint(0,10, size=(7,2))
random_array_4

array([[3, 6],
       [4, 9],
       [9, 9],
       [7, 1],
       [1, 3],
       [8, 1],
       [9, 0]])

In [17]:
np.random.random((3,5))

array([[0.40184764, 0.47768891, 0.0304047 , 0.17467762, 0.7177827 ],
       [0.59613031, 0.19317855, 0.45978195, 0.66630092, 0.54705621],
       [0.95279389, 0.23585301, 0.470124  , 0.82695457, 0.73340803]])

In [20]:
# Seed
np.random.seed(42)
random_array_5 = np.random.randint(0,10,size=(4,6))
random_array_5

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_6 = np.random.randint(1,10, size=(3,7))
# Find the unique numbers in the array you just created
random_array_6, np.unique(random_array_6)

(array([[2, 5, 8, 9, 9, 1, 9],
        [7, 9, 8, 1, 8, 8, 3],
        [1, 8, 3, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 7, 8, 9]))

In [24]:
# Find the 0'th index of the latest array you created
random_array_6[0]

array([2, 5, 8, 9, 9, 1, 9])

In [25]:
random_array_6[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [26]:
random_array_6[:2, :2]

array([[2, 5],
       [7, 9]])

In [27]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_7 = np.random.randint(0,10, size=(3,5))
random_ones = np.ones((3,5))

random_ones, random_array_7

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[9, 8, 6, 8, 7],
        [1, 0, 6, 6, 7],
        [4, 2, 7, 5, 2]]))

In [28]:
# Add the two arrays together
random_array_7 + random_ones

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [29]:
# Create another array of ones of shape (5, 3)
random_array_8 = np.ones((5,3))

In [31]:
random_array_7 + random_array_8

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [32]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))

In [33]:
# Subtract the new array of ones from the other most recent array
random_array_7 - ones

array([[ 8.,  7.,  5.,  7.,  6.],
       [ 0., -1.,  5.,  5.,  6.],
       [ 3.,  1.,  6.,  4.,  1.]])

In [34]:
random_array_8 * ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 